### PR TITLE
Automate build with GH actions

### PR DESCRIPTION
**Pull request by Raymo111**
Not sure if we want this. @Seshpenguin @espidev Merge this if it doesn't pose a security/pain/trouble risk

### CODE REVIEW

**Comment by espidev** [comment]
Would that actually host artifacts?

https://ci.espi.dev/job/smoothie-web/

**Comment by Seshpenguin** [comment]
This is probably a good idea, we want to lower dependance on our own personal infrastructure since we'll be handing this off next year.

**Comment by Raymo111** [comment]
What's CI?

**Comment by Raymo111** [comment]
I don't think it _hosts_ artifacts per se.
https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts

**Comment by espidev** [comment]
we can give it a try, though there are no tests to actually run lol
if there was one that hosted artifacts that'd be more useful

**Comment by Raymo111** [comment]
Lol the build passes shield is cool just on its own.

**Comment by espidev** [comment]
travis ci is more hip and popular though

**Comment by Seshpenguin** [comment]
Inb4 GitLab

**Comment by Raymo111** [comment]
lol nice

**Pull request merged**
